import {
  Company,
  Reply,
  PipelineStats,
  ActivityItem,
  DiscoveryResult,
} from "./types";

export const mockCompanies: Company[] = [
  {
    id: "c1",
    name: "NeuralFlow AI",
    description: "Building next-gen ML infrastructure for real-time model deployment and monitoring at scale.",
    website: "https://neuralflow.ai",
    location: "San Francisco, CA",
    stage: "replied",
    tags: ["MLOps", "Infrastructure", "Series A"],
    contacts: [
      {
        name: "Sarah Chen",
        title: "CTO & Co-founder",
        email: "sarah@neuralflow.ai",
        confidence: "verified",
        source: "LinkedIn + company website",
      },
      {
        name: "Mike Rodriguez",
        title: "Engineering Manager",
        email: "mike@neuralflow.ai",
        confidence: "guessed",
        source: "LinkedIn pattern match",
      },
    ],
    fundingStage: "Series A ($12M)",
    teamSize: "25-50",
    aiFocus: "ML Infrastructure & Deployment",
    discoveredAt: "2026-02-15T10:00:00Z",
    lastActivityAt: "2026-02-28T14:30:00Z",
    nextAction: {
      type: "respond",
      label: "Reply to Sarah",
      description: "Sarah asked about your ML experience and availability. Reply within 24h.",
      deadline: "2026-03-01T14:30:00Z",
      priority: "high",
    },
    researchSummary:
      "NeuralFlow is building Kubernetes-native ML deployment tools. Strong engineering culture, recently raised Series A from Sequoia. Hiring aggressively for ML platform roles. Good fit for your ML systems interest.",
    outreachDraft: {
      subject: "ML Infrastructure Intern - Excited about NeuralFlow's deployment tools",
      body: "Hi Sarah,\n\nI came across NeuralFlow's work on real-time ML deployment and was really impressed by your recent blog post on reducing inference latency by 40%.\n\nI'm a CS student at Stanford focusing on ML systems and infrastructure. Last summer, I built a model serving pipeline that handled 10K+ requests/sec using similar approaches to what NeuralFlow is pioneering.\n\nWould love to chat about potential internship opportunities on your platform team.\n\nBest,\nAlex",
      confidence: 87,
      generatedAt: "2026-02-18T09:00:00Z",
      contactUsed: {
        name: "Sarah Chen",
        title: "CTO & Co-founder",
        email: "sarah@neuralflow.ai",
        confidence: "verified",
        source: "LinkedIn + company website",
      },
    },
    timeline: [
      {
        id: "t1",
        type: "discovered",
        title: "Company Discovered",
        description: "Found via Y Combinator batch W24 scan",
        timestamp: "2026-02-15T10:00:00Z",
      },
      {
        id: "t2",
        type: "researched",
        title: "Research Completed",
        description: "Analyzed company profile, tech stack, and team. Strong ML infrastructure focus aligns with interests.",
        timestamp: "2026-02-16T11:00:00Z",
      },
      {
        id: "t3",
        type: "outreach_drafted",
        title: "Outreach Draft Created",
        description: "Generated personalized email to Sarah Chen (CTO). Confidence: 87%",
        timestamp: "2026-02-18T09:00:00Z",
        metadata: { confidence: 87 },
      },
      {
        id: "t4",
        type: "outreach_sent",
        title: "Outreach Email Sent",
        description: "Email sent to sarah@neuralflow.ai",
        timestamp: "2026-02-19T08:30:00Z",
      },
      {
        id: "t5",
        type: "reply_received",
        title: "Reply Received!",
        description: "Sarah responded positively - interested in discussing internship, asked about ML experience and availability.",
        timestamp: "2026-02-28T14:30:00Z",
        metadata: { urgency: "hot" },
      },
    ],
    notes: "Sarah seems very responsive. Company culture looks great from Glassdoor reviews.",
  },
  {
    id: "c2",
    name: "Cortex Labs",
    description: "AI-powered drug discovery platform accelerating pharmaceutical research with novel molecular generation.",
    website: "https://cortexlabs.bio",
    location: "South San Francisco, CA",
    stage: "outreach_sent",
    tags: ["BioTech", "Drug Discovery", "Seed"],
    contacts: [
      {
        name: "Dr. James Park",
        title: "CEO & Co-founder",
        email: "james@cortexlabs.bio",
        confidence: "verified",
        source: "Company website about page",
      },
      {
        name: "Lisa Wang",
        title: "Head of ML",
        email: "lwang@cortexlabs.bio",
        confidence: "guessed",
        source: "LinkedIn email pattern",
      },
    ],
    fundingStage: "Seed ($5M)",
    teamSize: "10-20",
    aiFocus: "Drug Discovery & Molecular ML",
    discoveredAt: "2026-02-17T14:00:00Z",
    lastActivityAt: "2026-02-25T10:00:00Z",
    nextAction: {
      type: "follow_up",
      label: "Send Follow-up",
      description: "No response after 5 days. Send a polite follow-up to James.",
      deadline: "2026-03-02T10:00:00Z",
      priority: "medium",
    },
    researchSummary:
      "Cortex Labs uses GNNs and transformer models for molecular property prediction. Small team but strong research output (2 NeurIPS papers). Founded by ex-Genentech scientists.",
    outreachDraft: {
      subject: "ML Intern Interested in AI-Driven Drug Discovery",
      body: "Hi James,\n\nI'm fascinated by Cortex Labs' approach to molecular generation using graph neural networks. Your NeurIPS paper on property-guided generation was really impressive.\n\nI'm a CS student with experience in GNNs and computational chemistry. Would love to discuss how I could contribute as an intern.\n\nBest,\nAlex",
      confidence: 72,
      generatedAt: "2026-02-20T15:00:00Z",
      contactUsed: {
        name: "Dr. James Park",
        title: "CEO & Co-founder",
        email: "james@cortexlabs.bio",
        confidence: "verified",
        source: "Company website about page",
      },
    },
    timeline: [
      {
        id: "t6",
        type: "discovered",
        title: "Company Discovered",
        description: "Found via Bay Area AI startup database",
        timestamp: "2026-02-17T14:00:00Z",
      },
      {
        id: "t7",
        type: "researched",
        title: "Research Completed",
        description: "Reviewed publications and tech blog. Strong alignment with computational biology interests.",
        timestamp: "2026-02-19T10:00:00Z",
      },
      {
        id: "t8",
        type: "outreach_drafted",
        title: "Outreach Draft Created",
        description: "Generated email to Dr. James Park. Confidence: 72%",
        timestamp: "2026-02-20T15:00:00Z",
        metadata: { confidence: 72 },
      },
      {
        id: "t9",
        type: "outreach_sent",
        title: "Outreach Email Sent",
        description: "Email sent to james@cortexlabs.bio",
        timestamp: "2026-02-25T10:00:00Z",
      },
    ],
    notes: "",
  },
  {
    id: "c3",
    name: "VoxAI",
    description: "Real-time voice AI for customer service automation, reducing wait times by 80% with natural conversation.",
    website: "https://voxai.com",
    location: "Palo Alto, CA",
    stage: "researched",
    tags: ["Voice AI", "NLP", "Series B"],
    contacts: [
      {
        name: "Emily Torres",
        title: "VP of Engineering",
        email: "emily.torres@voxai.com",
        confidence: "verified",
        source: "LinkedIn verified email",
      },
    ],
    fundingStage: "Series B ($35M)",
    teamSize: "50-100",
    aiFocus: "Voice AI & NLP",
    discoveredAt: "2026-02-20T09:00:00Z",
    lastActivityAt: "2026-02-26T16:00:00Z",
    nextAction: {
      type: "draft_outreach",
      label: "Draft Outreach Email",
      description: "Research complete. Draft a personalized email to Emily Torres.",
      deadline: "2026-03-03T09:00:00Z",
      priority: "medium",
    },
    researchSummary:
      "VoxAI has built a proprietary voice synthesis engine that handles real-time conversations. Series B from a16z. Strong NLP team, actively hiring. Good culture reviews on Blind.",
    outreachDraft: null,
    timeline: [
      {
        id: "t10",
        type: "discovered",
        title: "Company Discovered",
        description: "Found via Crunchbase AI startup filter",
        timestamp: "2026-02-20T09:00:00Z",
      },
      {
        id: "t11",
        type: "researched",
        title: "Research Completed",
        description: "Comprehensive research: tech stack, team, culture, and funding analysis complete.",
        timestamp: "2026-02-26T16:00:00Z",
      },
    ],
    notes: "Large company but has a dedicated internship program.",
  },
  {
    id: "c4",
    name: "Synthwave Robotics",
    description: "Autonomous mobile robots for warehouse logistics powered by vision transformers and sim-to-real transfer.",
    website: "https://synthwave.bot",
    location: "Berkeley, CA",
    stage: "discovered",
    tags: ["Robotics", "Computer Vision", "Seed"],
    contacts: [
      {
        name: "Alex Kim",
        title: "Founder",
        email: "alex@synthwave.bot",
        confidence: "unknown",
        source: "Guessed from domain",
      },
    ],
    fundingStage: "Seed ($3M)",
    teamSize: "5-10",
    aiFocus: "Robotics & Computer Vision",
    discoveredAt: "2026-02-27T11:00:00Z",
    lastActivityAt: "2026-02-27T11:00:00Z",
    nextAction: {
      type: "research",
      label: "Research Company",
      description: "New discovery. Research team, tech stack, and internship potential.",
      deadline: null,
      priority: "low",
    },
    researchSummary: null,
    outreachDraft: null,
    timeline: [
      {
        id: "t12",
        type: "discovered",
        title: "Company Discovered",
        description: "Found via Twitter/X AI community mentions",
        timestamp: "2026-02-27T11:00:00Z",
      },
    ],
    notes: "",
  },
  {
    id: "c5",
    name: "DataWeave AI",
    description: "Automated data pipeline construction using LLMs - turning natural language specs into production ETL.",
    website: "https://dataweave.ai",
    location: "San Francisco, CA",
    stage: "interview",
    tags: ["Data Engineering", "LLMs", "Series A"],
    contacts: [
      {
        name: "Rachel Green",
        title: "Head of Engineering",
        email: "rachel@dataweave.ai",
        confidence: "verified",
        source: "Direct introduction via Stanford network",
      },
    ],
    fundingStage: "Series A ($18M)",
    teamSize: "30-50",
    aiFocus: "Data Infrastructure & LLMs",
    discoveredAt: "2026-02-10T08:00:00Z",
    lastActivityAt: "2026-02-28T09:00:00Z",
    nextAction: {
      type: "schedule_interview",
      label: "Prepare for Interview",
      description: "Technical interview scheduled for March 3rd. Prepare system design answers.",
      deadline: "2026-03-03T14:00:00Z",
      priority: "high",
    },
    researchSummary:
      "DataWeave converts natural language to Airflow DAGs. Raised Series A from Greylock. Rachel Green is a Stanford alum, warm intro available via Prof. Martinez.",
    outreachDraft: {
      subject: "Stanford CS Student - Intern Role at DataWeave",
      body: "Hi Rachel,\n\nProf. Martinez suggested I reach out about internship opportunities at DataWeave...",
      confidence: 95,
      generatedAt: "2026-02-12T10:00:00Z",
      contactUsed: {
        name: "Rachel Green",
        title: "Head of Engineering",
        email: "rachel@dataweave.ai",
        confidence: "verified",
        source: "Direct introduction via Stanford network",
      },
    },
    timeline: [
      {
        id: "t13",
        type: "discovered",
        title: "Company Discovered",
        description: "Recommended by Prof. Martinez",
        timestamp: "2026-02-10T08:00:00Z",
      },
      {
        id: "t14",
        type: "researched",
        title: "Research Completed",
        description: "Deep dive into product, team, and tech. Strong LLM + data engineering focus.",
        timestamp: "2026-02-11T14:00:00Z",
      },
      {
        id: "t15",
        type: "outreach_sent",
        title: "Outreach Sent (Warm Intro)",
        description: "Sent via Prof. Martinez introduction to rachel@dataweave.ai",
        timestamp: "2026-02-13T09:00:00Z",
      },
      {
        id: "t16",
        type: "reply_received",
        title: "Positive Reply",
        description: "Rachel replied enthusiastically. Wants to set up a technical screen.",
        timestamp: "2026-02-18T11:00:00Z",
        metadata: { urgency: "hot" },
      },
      {
        id: "t17",
        type: "interview_scheduled",
        title: "Technical Interview Scheduled",
        description: "45-min technical interview on March 3rd, 2:00 PM PST. Focus: system design + LLM applications.",
        timestamp: "2026-02-28T09:00:00Z",
      },
    ],
    notes: "Warm intro makes this a strong lead. Prepare well for the technical screen.",
  },
  {
    id: "c6",
    name: "PixelMind",
    description: "AI-powered creative tools for designers - automated layout, color, and typography suggestions.",
    website: "https://pixelmind.design",
    location: "San Francisco, CA",
    stage: "researched",
    tags: ["Creative AI", "Design Tools", "Seed"],
    contacts: [
      {
        name: "Jordan Lee",
        title: "CTO",
        email: "jordan@pixelmind.design",
        confidence: "guessed",
        source: "LinkedIn + domain guess",
      },
    ],
    fundingStage: "Seed ($4M)",
    teamSize: "8-15",
    aiFocus: "Generative AI for Design",
    discoveredAt: "2026-02-22T13:00:00Z",
    lastActivityAt: "2026-02-24T10:00:00Z",
    nextAction: {
      type: "draft_outreach",
      label: "Draft Outreach Email",
      description: "Research done. Contact confidence is low - consider verifying email first.",
      deadline: null,
      priority: "low",
    },
    researchSummary:
      "PixelMind uses diffusion models for design automation. Small team, early stage. Interesting tech but may not have formal internship program.",
    outreachDraft: null,
    timeline: [
      {
        id: "t18",
        type: "discovered",
        title: "Company Discovered",
        description: "Found via Product Hunt AI launch list",
        timestamp: "2026-02-22T13:00:00Z",
      },
      {
        id: "t19",
        type: "researched",
        title: "Research Completed",
        description: "Small team, interesting generative AI work. May need to pitch internship concept.",
        timestamp: "2026-02-24T10:00:00Z",
      },
    ],
    notes: "Need to verify Jordan's email before outreach.",
  },
  {
    id: "c7",
    name: "SecureAI",
    description: "AI-powered cybersecurity platform for threat detection and automated incident response.",
    website: "https://secureai.io",
    location: "Mountain View, CA",
    stage: "done",
    tags: ["Cybersecurity", "AI", "Series B"],
    contacts: [
      {
        name: "Tom Bradley",
        title: "VP Engineering",
        email: "tom.bradley@secureai.io",
        confidence: "verified",
        source: "Company careers page",
      },
    ],
    fundingStage: "Series B ($40M)",
    teamSize: "80-120",
    aiFocus: "Security & Threat Detection",
    discoveredAt: "2026-02-08T09:00:00Z",
    lastActivityAt: "2026-02-22T16:00:00Z",
    nextAction: null,
    researchSummary:
      "Large team, formal internship program. However, primarily focused on security domain, not core ML.",
    outreachDraft: null,
    timeline: [
      {
        id: "t20",
        type: "discovered",
        title: "Company Discovered",
        description: "Found via LinkedIn job posting",
        timestamp: "2026-02-08T09:00:00Z",
      },
      {
        id: "t21",
        type: "researched",
        title: "Research Completed",
        description: "Good company but not aligned with ML infrastructure focus.",
        timestamp: "2026-02-10T14:00:00Z",
      },
      {
        id: "t22",
        type: "status_changed",
        title: "Marked as Done",
        description: "Decided not to pursue - focus area mismatch.",
        timestamp: "2026-02-22T16:00:00Z",
      },
    ],
    notes: "Passed - not aligned with ML focus.",
  },
  {
    id: "c8",
    name: "AgriTech AI",
    description: "Precision agriculture platform using satellite imagery and ML for crop yield optimization.",
    website: "https://agritechai.com",
    location: "Oakland, CA",
    stage: "followed_up",
    tags: ["Agriculture", "Computer Vision", "Series A"],
    contacts: [
      {
        name: "Maria Santos",
        title: "Engineering Lead",
        email: "maria@agritechai.com",
        confidence: "verified",
        source: "Met at AI meetup",
      },
    ],
    fundingStage: "Series A ($8M)",
    teamSize: "20-35",
    aiFocus: "Computer Vision & Remote Sensing",
    discoveredAt: "2026-02-12T10:00:00Z",
    lastActivityAt: "2026-02-27T09:00:00Z",
    nextAction: {
      type: "review",
      label: "Check for Response",
      description: "Follow-up sent 2 days ago. Check inbox for any replies.",
      deadline: "2026-03-04T09:00:00Z",
      priority: "low",
    },
    researchSummary:
      "AgriTech AI processes satellite imagery using vision transformers. Interesting CV application, growing team. Maria Santos is a strong contact from the AI meetup.",
    outreachDraft: {
      subject: "Following up - ML Intern Opportunity",
      body: "Hi Maria,\n\nGreat meeting you at the Bay Area AI meetup last week...",
      confidence: 90,
      generatedAt: "2026-02-15T11:00:00Z",
      contactUsed: {
        name: "Maria Santos",
        title: "Engineering Lead",
        email: "maria@agritechai.com",
        confidence: "verified",
        source: "Met at AI meetup",
      },
    },
    timeline: [
      {
        id: "t23",
        type: "discovered",
        title: "Company Discovered",
        description: "Met Maria Santos at Bay Area AI meetup",
        timestamp: "2026-02-12T10:00:00Z",
      },
      {
        id: "t24",
        type: "researched",
        title: "Research Completed",
        description: "Vision transformer work for agriculture. Great team culture.",
        timestamp: "2026-02-14T14:00:00Z",
      },
      {
        id: "t25",
        type: "outreach_sent",
        title: "Outreach Email Sent",
        description: "Sent follow-up from meetup conversation to maria@agritechai.com",
        timestamp: "2026-02-18T09:00:00Z",
      },
      {
        id: "t26",
        type: "follow_up_sent",
        title: "Follow-up Sent",
        description: "Polite follow-up after 9 days with no response.",
        timestamp: "2026-02-27T09:00:00Z",
      },
    ],
    notes: "Met Maria in person - warm lead but she may be busy.",
  },
];

export const mockReplies: Reply[] = [
  {
    id: "r1",
    companyId: "c1",
    companyName: "NeuralFlow AI",
    contactName: "Sarah Chen",
    contactEmail: "sarah@neuralflow.ai",
    subject: "Re: ML Infrastructure Intern - Excited about NeuralFlow's deployment tools",
    body: "Hi Alex,\n\nThanks for reaching out! Your experience with model serving pipelines sounds really relevant to what we're building.\n\nI'd love to learn more about your ML systems work. Could you share a bit more about:\n1. Your experience with Kubernetes-based deployments\n2. Any work with model optimization/quantization\n3. Your availability for the summer\n\nLooking forward to hearing from you!\n\nBest,\nSarah",
    receivedAt: "2026-02-28T14:30:00Z",
    urgency: "hot",
    status: "new",
    suggestedAction: "Reply with detailed ML experience and availability. Sarah is engaged - don't delay.",
    category: "interview_invite",
    snoozeUntil: null,
  },
  {
    id: "r2",
    companyId: "c5",
    companyName: "DataWeave AI",
    contactName: "Rachel Green",
    contactEmail: "rachel@dataweave.ai",
    subject: "Re: Stanford CS Student - Intern Role at DataWeave",
    body: "Hi Alex,\n\nGreat to hear from you! Prof. Martinez speaks very highly of your work.\n\nWe'd love to set up a technical interview. How does March 3rd at 2pm PST work for you? It'll be a 45-minute session focused on system design and LLM applications.\n\nPlease let me know!\n\nBest,\nRachel",
    receivedAt: "2026-02-18T11:00:00Z",
    urgency: "hot",
    status: "in_progress",
    suggestedAction: "Interview already scheduled. Prepare system design and LLM knowledge.",
    category: "interview_invite",
    snoozeUntil: null,
  },
  {
    id: "r3",
    companyId: "c7",
    companyName: "SecureAI",
    contactName: "HR Team",
    contactEmail: "careers@secureai.io",
    subject: "Thank you for your interest in SecureAI",
    body: "Dear Applicant,\n\nThank you for your interest in SecureAI. We've reviewed your inquiry and unfortunately, we don't have any openings that match your background at this time.\n\nWe'll keep your information on file for future opportunities.\n\nBest regards,\nSecureAI Recruiting",
    receivedAt: "2026-02-20T09:00:00Z",
    urgency: "cold",
    status: "done",
    suggestedAction: "No action needed. Generic rejection from HR.",
    category: "rejection",
    snoozeUntil: null,
  },
  {
    id: "r4",
    companyId: "c2",
    companyName: "Cortex Labs",
    contactName: "noreply@cortexlabs.bio",
    contactEmail: "noreply@cortexlabs.bio",
    subject: "Out of Office: Dr. James Park",
    body: "Thank you for your email. I am currently out of the office attending a conference and will return on March 3rd. I will respond to your email upon my return.\n\nFor urgent matters, please contact lisa@cortexlabs.bio.\n\nBest,\nJames",
    receivedAt: "2026-02-25T10:05:00Z",
    urgency: "warm",
    status: "snoozed",
    suggestedAction: "James is at a conference until March 3. Follow up after he returns.",
    category: "auto_reply",
    snoozeUntil: "2026-03-04T09:00:00Z",
  },
];

export const mockPipelineStats: PipelineStats = {
  totalCompanies: 8,
  byStage: {
    discovered: 1,
    researched: 2,
    outreach_sent: 1,
    followed_up: 1,
    replied: 1,
    interview: 1,
    done: 1,
  },
  actionItemsCount: 5,
  repliesPending: 2,
  outreachSentThisWeek: 3,
  interviewsScheduled: 1,
};

export const mockActivityFeed: ActivityItem[] = [
  {
    id: "a1",
    type: "reply_received",
    title: "Reply from NeuralFlow AI",
    description: "Sarah Chen responded to your outreach - wants to learn more about your ML experience.",
    timestamp: "2026-02-28T14:30:00Z",
    companyId: "c1",
    companyName: "NeuralFlow AI",
  },
  {
    id: "a2",
    type: "interview_scheduled",
    title: "Interview Scheduled - DataWeave AI",
    description: "Technical interview with Rachel Green on March 3rd, 2:00 PM PST.",
    timestamp: "2026-02-28T09:00:00Z",
    companyId: "c5",
    companyName: "DataWeave AI",
  },
  {
    id: "a3",
    type: "follow_up_sent",
    title: "Follow-up Sent to AgriTech AI",
    description: "Automatic follow-up sent to Maria Santos after 9 days.",
    timestamp: "2026-02-27T09:00:00Z",
    companyId: "c8",
    companyName: "AgriTech AI",
  },
  {
    id: "a4",
    type: "discovered",
    title: "New Company: Synthwave Robotics",
    description: "Discovered via Twitter/X AI community - autonomous warehouse robots.",
    timestamp: "2026-02-27T11:00:00Z",
    companyId: "c4",
    companyName: "Synthwave Robotics",
  },
  {
    id: "a5",
    type: "outreach_sent",
    title: "Outreach Sent to Cortex Labs",
    description: "Email sent to Dr. James Park about ML internship.",
    timestamp: "2026-02-25T10:00:00Z",
    companyId: "c2",
    companyName: "Cortex Labs",
  },
  {
    id: "a6",
    type: "researched",
    title: "Research Complete: PixelMind",
    description: "Completed research on PixelMind's generative AI design tools.",
    timestamp: "2026-02-24T10:00:00Z",
    companyId: "c6",
    companyName: "PixelMind",
  },
];

export const mockDiscoveryResult: DiscoveryResult = {
  companiesFound: 12,
  newCompanies: 3,
  source: "Y Combinator W24 + Crunchbase AI filter",
  scanDate: "2026-02-27T08:00:00Z",
  summary:
    "Scanned 45 Bay Area AI startups. Found 12 matches, 3 new companies added to pipeline. Focus areas: ML infrastructure, NLP, and computer vision.",
  topFinds: [
    { name: "Synthwave Robotics", reason: "Vision transformers + sim-to-real, early stage = more impactful intern role" },
    { name: "PixelMind", reason: "Generative AI for design, interesting diffusion model work" },
    { name: "VoxAI", reason: "Series B with strong NLP team, formal internship program" },
  ],
};
